# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra', '0002_auto_20161026_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=b'')),
            ],
        ),
    ]
