# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra', '0003_imgquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
