# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra', '0004_auto_20161027_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
