# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobra', '0006_auto_20161102_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[('LNK', 'link'), ('SMS', 'sms'), ('EML', 'email'), ('BT', 'braintree')], default='LNK', max_length=15),
        ),
    ]
